### ISSUE TITLE
comprehension of getNearestPointOnSegment

### ISSUE THREAD

**Issue by as142** [indazoo/OldReprapMendel#1]
Hi there, When I was learning and trying to understand the function "getNearestPointOnSegment" in OldReprapMendel/old_files/miscellaneous/python-beanshell-scripts/fabmetheus_utilities/euclidean.py, I was confused about the description of its delivered function. My understanding of this code snippet is "get the nearest point on the segment". Do I understand that right?

**Comment by indazoo** [comment]
Hi, I forked this repo mainly for the hardware files. You found Skeinforge in it. Great.
I think it is the wrong repo for Skeinforge. I'm not one of the main contributors. I have my own Skeinforge version forked from another repo though, but it is not public yet. I have no more time now, maybe later, have to go to work.
